apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: abhay-reorder-pipeline
  labels:
    scenarios.ai.sap.com/id: "abhay-reorder-learning"
    ai.sap.com/version: "0.0.1"
  annotations:
    scenarios.ai.sap.com/name: "abhay-reorder-learning"
    scenarios.ai.sap.com/description: "Abhay's Predictive Reorder Level Scenario"
    executables.ai.sap.com/name: "abhay-reorder-pipeline"
    executables.ai.sap.com/description: "Predict reorder levels from HANA sales history"
spec:
  entrypoint: mytemplate
  templates:
    - name: mytemplate
      container:
        image: "docker.io/n8nforabhay/aicore-reorder-demo:v1"
        command: ["python", "predict_reorder.py"]
        env:
          - name: HANA_HOST
            valueFrom:
              secretKeyRef:
                name: hana-connection-secret
                key: HANA_HOST
          - name: HANA_PORT
            valueFrom:
              secretKeyRef:
                name: hana-connection-secret
                key: HANA_PORT
          - name: HANA_USER
            valueFrom:
              secretKeyRef:
                name: hana-connection-secret
                key: HANA_USER
          - name: HANA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hana-connection-secret
                key: HANA_PASSWORD
